# Generated by Django 4.2 on 2023-11-28 17:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rallocatorapp', '0002_alter_roomallocation_options_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Have_Own_System',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SystemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('From', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('To', models.TimeField(null=True)),
                ('Batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.batch')),
                ('students', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Batch', chained_model_field='Batch', limit_choices_to={'Have_Own_System': False, 'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('system', models.ForeignKey(limit_choices_to={'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.system')),
            ],
        ),
    ]
