# Generated by Django 4.2 on 2023-11-28 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rallocatorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomallocation',
            options={'verbose_name_plural': 'RoomAllocation'},
        ),
        migrations.RenameField(
            model_name='district',
            old_name='State',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='Person',
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.branch_name'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='branch_name',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='name', limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.district'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='Batch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Branch', chained_model_field='branch', limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.batch'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='From',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='Room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Branch', chained_model_field='Branch', limit_choices_to={'isactive': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rallocatorapp.room'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='To',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='ResponsibleTrainer',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResponsibleTrainer', to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
    ]
