# Generated by Django 4.2 on 2023-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallocatorapp', '0002_alter_roomallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='ActualDateofReturn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='DateofPurchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='DateofReturn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
